config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:product_id', to: 'carts#removeone', as: :remove_one
  end
  
  resources :transactions, only: [:new, :create]
  resources :orders, only: [:index, :destroy]

  namespace :admin do
    root to: 'products#index'
    resources :products, only: [:index, :new, :show, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :destroy] 
  end

  namespace :api do
    namespace :v1 do
      resources :orders
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :products
    has_many :orders
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :product
  belongs_to :admin
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
  belongs_to :admin

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :products, through: :orders


  def current_user_cart
    "cart#{id}"
  end

  def add_to_cart(product_id)
    $redis.hincrby current_user_cart, product_id, 1
  end

  def remove_from_cart(product_id)
    $redis.hdel current_user_cart, product_id
  end

  def remove_one_from_cart(product_id)
    $redis.hincrby current_user_cart, product_id, -1
  end

  def cart_count
    quantities = $redis.hvals "cart#{id}"
    quantities.reduce(0) { |sum, qty| sum + qty.to_i }
  end

  def cart_total_price
    get_cart_products_with_qty.map { |product, qty| product.price * qty.to_i }.reduce(:+)
  end

  def get_cart_products_with_qty
    cart_ids = []
    cart_qtys = []
    ($redis.hgetall current_user_cart).map do |key, value|
      cart_ids << key
      cart_qtys << value
    end
    cart_products = Product.find(cart_ids)
    cart_products.zip(cart_qtys)
  end

  def purchase_cart_products!
    get_cart_products_with_qty.each do |product, qty|
      self.orders.create(user: self, product: product, quantity: qty, admin_id: product.admin_id)
    end
    $redis.del current_user_cart
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

before_action :authenticate_admin!

  def index
    @orders = current_admin.orders
  end

  def destroy
  	order = Order.find_by_id(params[:id])
  	order.update_attribute(:cancel, true)
	flash[:notice] = "Order got cancelled!"
	UserMailer.with(user: current_admin.email).cancel_email
	redirect_to admin_orders_path
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @products = current_admin.products.all
  end

  def show
    @product = find_product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.admin_id = current_admin.id
    if @product.save
      flash[:notice] = "Product added!"
      redirect_to admin_products_path
    else
      flash[:notice] = "Product can't be blank!"
      render 'admin/products/new'
    end
  end

  def edit
    @product = find_product
  end

  def update
    @product = find_product
    if @product.update(product_params)
      flash[:notice] = "Product updated!"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    Product.destroy(params[:id])
    flash[:notice] = "Product removed!"
    redirect_to admin_products_path
  end

  def find_product
    product = Product.find_by_id(params[:id])
    if product.present?
      if product.admin == current_admin
        product
      else
        flash[:notice] = "This Product do not belongs to you!"
        redirect_to admin_products_path
      end
    else
      flash[:notice] = "This Product do not belongs to you!"
      redirect_to admin_products_path
    end
  end

  private

    def product_params
      params.require(:product).permit(:name, :description, :price)
    end

end

app/controllers/api/v1/orders_controller.rb
class Api::V1::ProductsController
  def index
    @products = Product.all
    render json: @products
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!

  def show
    @cart_products_with_qty = current_user.get_cart_products_with_qty
    @cart_total = current_user.cart_total_price
  end

  def add
    if current_user.cart_count.zero?
      current_user.add_to_cart(params[:product_id])
    else
      admin_ids = current_user.get_cart_products_with_qty.map{|p| p.first.admin_id}
      product = Product.find(params[:product_id])
      if admin_ids.include? product.admin_id
        current_user.add_to_cart(params[:product_id])
      else
        flash[:notice] = "You can not add products from different shops"
      end
    end

    redirect_to cart_path
  end

  def remove
    current_user.remove_from_cart(params[:product_id])
    redirect_to cart_path
  end

  def removeone
    current_user.remove_one_from_cart(params[:product_id])
    redirect_to cart_path
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

before_action :authenticate_user!

  def index
    @orders = current_user.orders
  end

  def destroy
  	order = Order.find_by_id(params[:id])
  	order.update_attribute(:cancel, true)
  	flash[:notice] = "Order got cancelled!"
  	UserMailer.with(user: current_user.email).cancel_email
  	redirect_to orders_path
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

    before_action :authenticate_user!
    before_action :check_cart!

    def new
    end

    def create
      current_user.purchase_cart_products!
      UserMailer.with(user: current_user.email).order_create_email
      flash[:notice] = "Congratulations! We'll try to get you your items as soon as possible!"
      redirect_to root_url
    end


    private

      def check_cart!
        if current_user.get_cart_products_with_qty.blank?
          redirect_to root_url, alert: "Please add some items to your cart before processing your transaction!"
        end
      end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/admin/orders/_admin_order.html.slim
tr
  td #{ admin_order.user.email }
  td #{ admin_order.product.try(:name) }
  td #{ admin_order.quantity }
  td #{ admin_order.created_at.getlocal.strftime("%e-%m-%y %H:%M") }
  td #{ admin_order.cancel }
  td = link_to 'Cancel', admin_order_path(admin_order), method: :delete

app/views/admin/orders/index.html.slim
h1.jumbotron Admin | Orders

.container
  .row
    .col-12.card
      table.table
        thead
          th User
          th Product
          th Quantity
          th Order Time
          th Active
        tbody
        = render partial: "admin_order", collection: @orders

app/views/admin/products/_admin_product.html.slim
tr
  td #{ admin_product.name }
  td #{ admin_product.description }
  td #{ admin_product.price }
  td = link_to 'Edit', edit_admin_product_path(admin_product)
  td = link_to 'View', admin_product_path(admin_product)
  td = link_to 'Delete', admin_product_path(admin_product), method: :delete

app/views/admin/products/edit.html.slim
h1.jumbotron Edit Product

.container
  = simple_form_for [:admin, @product], class: "form-horizontal" do |f|
    = f.input :name
    = f.input :description
    = f.input :price


    = f.button :submit

  = link_to 'Back to Product List', admin_products_path

app/views/admin/products/index.html.slim
h1.jumbotron Admin | Products

.container
  .row
    = link_to 'Add Product', new_admin_product_path
    .col-12.card
      table.table
        thead
          th Name
          th Description
          th Price
        tbody
        = render partial: "admin_product", collection: @products

app/views/admin/products/new.html.slim
h1.jumbotron Add a Product

.container
  = simple_form_for [:admin, @product], class: "form-horizontal" do |f|
    = f.input :name
    = f.input :description
    = f.input :price
  

    = f.button :submit

  = link_to 'Back to Product List', admin_products_path

app/views/admin/products/show.html.slim
h1.jumbotron #{ @product.name.capitalize }
.container
  .card
    .card-body
      p = @product.description
      p <small> SGD </small> #{ @product.price }

app/views/carts/show.html.slim
h1.jumbotron Your Shopping Cart!

.container
  .row
    table.table
      thead
        th Name
        th Price
        th Quantity
        th Subtotal
      tbody
        - @cart_products_with_qty.each do |array|
          - product = array[0]
          - qty = array[1]
          tr
            td.align-middle = product.name
            td.align-middle = product.price
            td.align-middle = qty
            td.align-middle = product.price * qty.to_i
            td.align-middle
              = link_to '+', add_to_cart_path(product), method: :put, class: "btn"
              = link_to '-', remove_one_cart_path(product), method: :put, class: "btn"
              = link_to 'Remove', remove_from_cart_path(product), method: :put, class: "btn btn-danger"

        tr.font-weight-bold
          td colspan="3"
            h5 Total
          td
            h5 = @cart_total

  =link_to "Checkout", new_transaction_path, class: "btn btn-success" unless current_user.get_cart_products_with_qty.blank?

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title ShoppingAppRedo
    = csrf_meta_tags
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .navbar
      .container
        - unless user_signed_in? || admin_signed_in?
          .navlink = link_to 'Shop Login', new_admin_session_path  
          .navlink = link_to 'User Login', new_user_session_path
        - if user_signed_in?
          .navlink = link_to 'Home', products_path
          .navlink = link_to 'Cart (' + "#{current_user.cart_count}" + ')', cart_path
          .navlink = link_to 'Orders', orders_path
          .navlink = link_to "Logout(#{current_user.email})", destroy_user_session_path
        - if admin_signed_in?
          h4 Shop
          .navlink = link_to 'Products', admin_products_path
          .navlink = link_to 'Orders', admin_orders_path
          .navlink = link_to "Logout(#{current_admin.email})", destroy_admin_session_path

    - flash.each do |name, msg|
       = content_tag :div, msg, class: name
    = yield

app/views/orders/index.html.slim
h1.jumbotron User | Orders

.container
  .row
    .col-12.card
      table.table
        thead
          th User
          th Product
          th Quantity
          th Order Time
          th Active

        tbody
        - @orders.each do |order|
          tr
            td #{ order.user.email }
            td #{ order.product.try(:name) }
            td #{ order.quantity }
            td #{ order.created_at.getlocal.strftime("%e-%m-%y %H:%M") }
            td #{ !order.cancel }
            td = link_to 'Cancel', order_path(order), method: :delete

app/views/products/index.html.slim
h1.jumbotron Welcome to Shopping App!

.container
  .row
    = render partial: "shared/product", collection: @products

app/views/products/show.html.slim
h1.jumbotron #{ @product.name.capitalize }
.container
  .card
    .card-body
      p = @product.description
      p <small> SGD </small> #{ @product.price }
      = link_to 'Add to Cart', add_to_cart_path(@product), method: :put
    .card-footer
      = link_to 'Back to Product List', products_path

app/views/shared/_product.html.slim
.card
  .card-body
    .card-title
      p #{ product.name }
    .card-text
      p <small> SGD </small> #{ product.price }
    .card-footer
      = link_to 'View Product', product_path(product)

app/views/transactions/new.html.slim
h1.jumbotron Checkout

.container.card.p-5
  h2 New Transaction
  = form_tag transactions_path do
    #dropin
    = submit_tag "Pay $ #{current_user.cart_total_price}"
br
br